name: Deploy to Environment

on:
  push:
    branches: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com/production  # Optional: Environment URL
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        run: |
          echo "Deploying to production environment"
          echo "Using API key: ${{ secrets.PRODUCTION_API_KEY }}"