name: Test Release Version

on:
    workflow_dispatch

jobs: 
    Test-Release: 
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Get All Releases
              id: releases
              run: |
                releases=$(gh release list --repo ${{ github.repository }} --json tagName,createdAt)
                echo $releases
            
            - name: Sort and Select Latest Release
              run: |
                filter1 = '.[] | {tagName, createdAt}'
                sort_field='createdAt'
                sorted_releases=$(echo "$releases" | jq -s "$filter1" | sort_by("sort_field") | reverse)
                latest_release=$(echo "$sorted_releases" | head -n 1 | jq -r '.tagName')
                echo "Latest release version: $latest_release"
