name: Test Release Version

on:
    workflow_dispatch

jobs: 
    Test-Release: 
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Get All Releases
              id: get_releases
              run: |
                releases=$(gh release list --repo ${{ github.repository }} --json tagName,createdAt)
                echo "$releases" > releases.json
            
            - name: Sort and Select Latest Release
              run: |
                sorted_releases=$(cat releases.json | jq -s '.[0] | sort_by(.createdAt) | reverse')
                latest_release=$(echo "$sorted_releases" | jq -r '.[0].tagName')
                echo "Latest release version: $latest_release"
