name: Test Release Version

on:
    workflow_dispatch

jobs: 
    Test-Release: 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Get All Releases
              id: releases
              run: |
                releases=$(gh release view --json tag_name --limit 100)
            
            - name: Extract Latest Version
              run: |
                latest_version=$(echo "$releases" | jq -r '.[0].tag_name')
                echo "Latest release version: $latest_version"