name: Test Release Version

on:
    workflow_dispatch

jobs: 
    Test-Release: 
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Get All Releases
              id: releases
              run: |
                releases=$(gh release list --repo ${{ github.repository }} --json tagName,createdAt)
            
            - name: Sort and Select Latest Release
              run: |
                sorted_releases=$(echo "$releases" | jq -s ".[] | {tagName, createdAt}" | sort_by(createdAt) | reverse)
                latest_release=$(echo "$sorted_releases" | head -n 1 | jq -r '.tagName')
                echo "Latest release version: $latest_release"
